services:
  # golang
  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./build/dockerfiles/app/Dockerfile
    volumes:
      - ./app:/usr/local/go/src/react_go_app/app
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}

  # postgresql
  db:
    container_name: ${DB_HOST}
    build:
      context: .
      dockerfile: ./build/dockerfiles/postgresql/Dockerfile
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./app/database/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432

volumes:
  db-store: